DROP DATABASE IF EXISTS manosverdes;
CREATE DATABASE manosverdes CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE manosverdes;
\n-- Combined generated by run_all_sql.ps1\n

-- Begin file: script.sql


  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;


CREATE TABLE rol (
  id          TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  clave       VARCHAR(20)  NOT NULL UNIQUE,
  nombre      VARCHAR(60)  NOT NULL,
  descripcion VARCHAR(255) NULL,
  creado_en   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

INSERT INTO rol (clave, nombre, descripcion) VALUES
('admin',  'Administrador', 'Acceso total al sistema'),
('centro', 'Centro de Reciclaje', 'Gestiona centros, materiales y contenido'),
('app',    'Usuario App', 'Usuario final de la aplicación');

CREATE TABLE usuario (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  nombre           VARCHAR(120) NOT NULL,
  apellido_paterno VARCHAR(120) NOT NULL,
  apellido_materno VARCHAR(120) NULL,
  email            VARCHAR(180) NOT NULL UNIQUE,
  telefono         VARCHAR(32)  NULL,
  fecha_nacimiento DATE         NULL,
  avatar_key       VARCHAR(600) NULL,
  estado           ENUM('activo','inactivo','bloqueado') NOT NULL DEFAULT 'activo',
  rol_id           TINYINT UNSIGNED NOT NULL,
  creado_en        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_usuario_rol
    FOREIGN KEY (rol_id) REFERENCES rol(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  INDEX idx_usuario_rol (rol_id),
  INDEX idx_usuario_estado (estado)
) ENGINE=InnoDB;

CREATE TABLE usuario_auth (
  usuario_id          INT PRIMARY KEY,
  password_hash       VARCHAR(255) NULL,
  email_verificado    TINYINT NOT NULL DEFAULT 0,
  email_verificado_en DATETIME NULL,
  intentos_fallidos   TINYINT UNSIGNED NOT NULL DEFAULT 0,
  ultimo_intento_en   DATETIME NULL,
  bloqueado_hasta     DATETIME NULL,
  actualizado_en      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ua_usuario
    FOREIGN KEY (usuario_id) REFERENCES usuario(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  INDEX idx_ua_bloqueo (bloqueado_hasta),
  INDEX idx_ua_verificado (email_verificado)
) ENGINE=InnoDB;

CREATE TABLE sesion (
  id          BIGINT AUTO_INCREMENT PRIMARY KEY,
  usuario_id  INT NOT NULL,
  token_hash  CHAR(64) NOT NULL UNIQUE,
  emitido_en  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expira_en   DATETIME NOT NULL,
  activo      TINYINT NOT NULL DEFAULT 1,
  cerrado_en  DATETIME NULL,
  ip          VARCHAR(64) NULL,
  user_agent  VARCHAR(255) NULL,
  creado_en   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_sesion_usuario
    FOREIGN KEY (usuario_id) REFERENCES usuario(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  INDEX idx_sesion_usuario (usuario_id),
  INDEX idx_sesion_expira (expira_en),
  INDEX idx_sesion_activo (activo)
) ENGINE=InnoDB;


CREATE TABLE codigo_otp (
  id          BIGINT AUTO_INCREMENT PRIMARY KEY,
  usuario_id  INT NOT NULL,
  tipo        ENUM('email_verificacion','password_reset') NOT NULL,
  codigo_hash CHAR(64) NOT NULL,
  expira_en   DATETIME NOT NULL,
  usado       TINYINT NOT NULL DEFAULT 0,
  usado_en DATETIME NULL AFTER usado;
  intentos    TINYINT UNSIGNED NOT NULL DEFAULT 0,
  creado_en   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_codigo_otp_usuario
    FOREIGN KEY (usuario_id) REFERENCES usuario(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  UNIQUE KEY uq_otp_usuario_tipo (usuario_id, tipo),
  INDEX idx_otp_expira (expira_en),
  INDEX idx_otp_usado (usado)
) ENGINE=InnoDB;


-- End file: script.sql


-- Begin file: scriptbd.sql


  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;


-- =========================
-- ROLES
-- =========================
CREATE TABLE rol (
  id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  clave VARCHAR(20) NOT NULL UNIQUE,
  nombre VARCHAR(60) NOT NULL,
  descripcion VARCHAR(255),
  creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

INSERT INTO rol (clave, nombre) VALUES
('admin','Administrador'),
('centro','Centro'),
('app','Usuario');

-- =========================
-- GEO PERÚ
-- =========================
CREATE TABLE departamento (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE provincia (
  id INT AUTO_INCREMENT PRIMARY KEY,
  departamento_id INT NOT NULL,
  nombre VARCHAR(120) NOT NULL,
  UNIQUE KEY uq_provincia (departamento_id, nombre),
  FOREIGN KEY (departamento_id) REFERENCES departamento(id)
)ENGINE=InnoDB;

CREATE TABLE distrito (
  id INT AUTO_INCREMENT PRIMARY KEY,
  provincia_id INT NOT NULL,
  nombre VARCHAR(120) NOT NULL,
  UNIQUE KEY uq_distrito (provincia_id, nombre),
  FOREIGN KEY (provincia_id) REFERENCES provincia(id)
)ENGINE=InnoDB; 

-- =========================
-- USUARIO
-- =========================
CREATE TABLE usuario (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  apellido_paterno VARCHAR(120) NOT NULL,
  apellido_materno VARCHAR(120),
  email VARCHAR(180) NOT NULL UNIQUE,
  telefono VARCHAR(32),
  fecha_nacimiento DATE,
  avatar_key VARCHAR(600),
  estado ENUM('activo','inactivo','bloqueado') NOT NULL DEFAULT 'activo',
  rol_id TINYINT UNSIGNED NOT NULL,
  creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (rol_id) REFERENCES rol(id),
  INDEX idx_usuario_rol (rol_id),
  INDEX idx_usuario_estado (estado)
) ENGINE=InnoDB;

-- =========================
-- AUTH
-- =========================
CREATE TABLE usuario_auth (
  usuario_id INT PRIMARY KEY,
  password_hash VARCHAR(255),
  email_verificado TINYINT NOT NULL DEFAULT 0,
  email_verificado_en DATETIME,
  intentos_fallidos TINYINT UNSIGNED NOT NULL DEFAULT 0,
  bloqueado_hasta DATETIME,
  actualizado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES usuario(id)
    ON DELETE CASCADE
) ENGINE=InnoDB;

-- =========================
-- OTP
-- =========================
CREATE TABLE codigo_otp (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  usuario_id INT NOT NULL,
  tipo ENUM('email_verificacion','password_reset') NOT NULL,
  codigo_hash CHAR(64) NOT NULL,
  expira_en DATETIME NOT NULL,
  usado TINYINT NOT NULL DEFAULT 0,
  creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_otp_usuario_tipo (usuario_id, tipo),
  FOREIGN KEY (usuario_id) REFERENCES usuario(id)
    ON DELETE CASCADE
) ENGINE=InnoDB;

-- =========================
-- MATERIALES
-- =========================
CREATE TABLE material_categoria (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL UNIQUE,
  icono VARCHAR(600),
  activo TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE material_subcategoria (
  id INT AUTO_INCREMENT PRIMARY KEY,
  categoria_id INT NOT NULL,
  nombre VARCHAR(120) NOT NULL,
  activo TINYINT NOT NULL DEFAULT 1,
  UNIQUE KEY uq_subcat (categoria_id,nombre),
  FOREIGN KEY (categoria_id) REFERENCES material_categoria(id)
) ENGINE=InnoDB;

CREATE TABLE material (
  id INT AUTO_INCREMENT PRIMARY KEY,
  subcategoria_id INT NOT NULL,
  nombre VARCHAR(120) NOT NULL,
  icono VARCHAR(1000),
  elegible TINYINT NOT NULL DEFAULT 1,
  activo TINYINT NOT NULL DEFAULT 1,
  UNIQUE KEY uq_material (subcategoria_id,nombre),
  FOREIGN KEY (subcategoria_id) REFERENCES material_subcategoria(id)
) ENGINE=InnoDB;

-- =========================
-- CENTRO
-- =========================
CREATE TABLE centro_tipo (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL UNIQUE
) ENGINE=InnoDB;

INSERT INTO centro_tipo (nombre) VALUES
('Centro de acopio'),
('Recicladora industrial'),
('Municipal'),
('Empresa privada'),
('Asociación / ONG');

CREATE TABLE centro (
  id INT AUTO_INCREMENT PRIMARY KEY,
  usuario_id INT NOT NULL UNIQUE,
  nombre VARCHAR(150) NOT NULL,
  direccion VARCHAR(255),
  distrito_id INT NOT NULL,
  tipo_id INT,
  telefono VARCHAR(32),
  horario VARCHAR(255),
  lat DECIMAL(10,6),
  lng DECIMAL(10,6),
  estado ENUM('activo','inactivo') NOT NULL DEFAULT 'activo',
  FOREIGN KEY (usuario_id) REFERENCES usuario(id),
  FOREIGN KEY (distrito_id) REFERENCES distrito(id),
  FOREIGN KEY (tipo_id) REFERENCES centro_tipo(id)
) ENGINE=InnoDB;

CREATE TABLE centro_representante (
  centro_id INT PRIMARY KEY,
  ruc CHAR(11),
  razon_social VARCHAR(180),
  contacto_nombre VARCHAR(120),
  contacto_cargo VARCHAR(80),
  contacto_tel VARCHAR(32),
  contacto_email VARCHAR(180),
  web_url VARCHAR(255),
  FOREIGN KEY (centro_id) REFERENCES centro(id)
    ON DELETE CASCADE
) ENGINE=InnoDB;

-- =========================
-- CENTRO FOTOS (GCP)
-- =========================
CREATE TABLE centro_foto (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  centro_id INT NOT NULL,
  foto_key VARCHAR(600) NOT NULL,
  creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (centro_id) REFERENCES centro(id)
    ON DELETE CASCADE,
  INDEX idx_centro_foto (centro_id)
) ENGINE=InnoDB;

-- =========================
-- PRECIOS
-- =========================
CREATE TABLE centro_material_precio (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  centro_id INT NOT NULL,
  material_id INT NOT NULL,
  precio_kg DECIMAL(10,2) NOT NULL,
  moneda CHAR(3) NOT NULL DEFAULT 'PEN',
  UNIQUE KEY uq_cmp (centro_id,material_id),
  FOREIGN KEY (centro_id) REFERENCES centro(id),
  FOREIGN KEY (material_id) REFERENCES material(id)
) ENGINE=InnoDB;

-- =========================
-- COMENTARIOS Y RATING
-- =========================
CREATE TABLE centro_comentario (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  centro_id INT NOT NULL,
  usuario_id INT NOT NULL,
  texto VARCHAR(600) NOT NULL,
  creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (centro_id) REFERENCES centro(id),
  FOREIGN KEY (usuario_id) REFERENCES usuario(id)
) ENGINE=InnoDB;

CREATE TABLE centro_rating (
  centro_id INT NOT NULL,
  usuario_id INT NOT NULL,
  estrellas TINYINT NOT NULL,
  PRIMARY KEY (centro_id,usuario_id),
  CHECK (estrellas BETWEEN 1 AND 5),
  FOREIGN KEY (centro_id) REFERENCES centro(id),
  FOREIGN KEY (usuario_id) REFERENCES usuario(id)
) ENGINE=InnoDB;
CREATE TABLE material_info (
  material_id INT PRIMARY KEY,
  descripcion TEXT,
  beneficios TEXT,
  proceso TEXT,
  ideas TEXT,
  contaminacion TEXT,
  FOREIGN KEY (material_id) REFERENCES material(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- =========================
-- DATOS DE PRUEBA
-- =========================

-- USUARIOS DE PRUEBA
INSERT INTO usuario (nombre, apellido_paterno, apellido_materno, email, telefono, rol_id, estado) VALUES
('Admin', 'Manos Verdes', NULL, 'admin@manosverdes.test', '987654321', 1, 'activo'),
('Centro', 'Reciclaje', 'Lima', 'centro@manosverdes.test', '987654322', 2, 'activo'),
('Juan', 'Pérez', 'García', 'usuario@manosverdes.test', '987654323', 3, 'activo');

-- CREDENCIALES (Contraseña: Test123456 → Hash bcryptjs)
INSERT INTO usuario_auth (usuario_id, password_hash, email_verificado, intentos_fallidos) VALUES
(1, '$2b$10$DrqLB2cmR6LhkP5auGAXfu5M2ywvQT92F84e3YhZqSy7L7hEe1HD.', 1, 0),
(2, '$2b$10$DrqLB2cmR6LhkP5auGAXfu5M2ywvQT92F84e3YhZqSy7L7hEe1HD.', 1, 0),
(3, '$2b$10$DrqLB2cmR6LhkP5auGAXfu5M2ywvQT92F84e3YhZqSy7L7hEe1HD.', 1, 0);

-- CATEGORÍAS DE MATERIALES
INSERT INTO material_categoria (nombre, icono, activo) VALUES
('Plásticos', 'plastic.png', 1),
('Vidrio', 'glass.png', 1),
('Papel y Cartón', 'paper.png', 1),
('Metales', 'metal.png', 1),
('Electrónicos', 'electronic.png', 1),
('Peligrosos', 'danger.png', 1);

-- SUBCATEGORÍAS DE PLÁSTICOS
INSERT INTO material_subcategoria (categoria_id, nombre, activo) VALUES
(1, 'PET (botellas)', 1),
(1, 'HDPE (bolsas)', 1),
(1, 'PVC', 1);

-- SUBCATEGORÍAS DE VIDRIO
INSERT INTO material_subcategoria (categoria_id, nombre, activo) VALUES
(2, 'Botellas claras', 1),
(2, 'Botellas verdes', 1),
(2, 'Botellas marrones', 1);

-- SUBCATEGORÍAS DE PAPEL
INSERT INTO material_subcategoria (categoria_id, nombre, activo) VALUES
(3, 'Periódicos', 1),
(3, 'Cartón corrugado', 1),
(3, 'Papel blanco', 1);

-- SUBCATEGORÍAS DE METALES
INSERT INTO material_subcategoria (categoria_id, nombre, activo) VALUES
(4, 'Aluminio', 1),
(4, 'Acero', 1),
(4, 'Cobre', 1);

-- SUBCATEGORÍAS PELIGROSOS
INSERT INTO material_subcategoria (categoria_id, nombre, activo) VALUES
(6, 'Residuos Quirúrgicos', 1),
(6, 'Residuos Hospitalarios', 1),
(6, 'Químicos Tóxicos', 1);

-- MATERIALES - PLÁSTICOS
INSERT INTO material (subcategoria_id, nombre, elegible, activo) VALUES
(1, 'Botella PET transparente', 1, 1),
(1, 'Botella PET de color', 1, 1),
(2, 'Bolsa HDPE', 1, 1),
(3, 'Tubería PVC', 1, 1);

-- MATERIALES - VIDRIO
INSERT INTO material (subcategoria_id, nombre, elegible, activo) VALUES
(4, 'Botella clara', 1, 1),
(4, 'Frasco transparente', 1, 1),
(5, 'Botella verde', 1, 1),
(6, 'Botella marrón', 1, 1);

-- MATERIALES - PAPEL
INSERT INTO material (subcategoria_id, nombre, elegible, activo) VALUES
(7, 'Periódico', 1, 1),
(8, 'Cartón de caja', 1, 1),
(9, 'Papel de oficina', 1, 1);

-- MATERIALES - METALES
INSERT INTO material (subcategoria_id, nombre, elegible, activo) VALUES
(10, 'Lata de aluminio', 1, 1),
(10, 'Papel aluminio', 1, 1),
(11, 'Tubo de acero', 1, 1),
(12, 'Cable de cobre', 1, 1);

-- MATERIALES PELIGROSOS (elegible=0 → NO se puede registrar para acopio)
INSERT INTO material (subcategoria_id, nombre, elegible, activo) VALUES
(13, 'Gasas quirúrgicas contaminadas', 0, 1),
(13, 'Agujas y jeringas', 0, 1),
(14, 'Sangre y fluidos corporales', 0, 1),
(15, 'Ácido sulfúrico', 0, 1),
(15, 'Pesticidas', 0, 1);

-- DATOS GEOGRAFÍA PERÚ (EJEMPLO)
INSERT INTO departamento (nombre) VALUES
('Lima');

INSERT INTO provincia (departamento_id, nombre) VALUES
(1, 'Lima');

INSERT INTO distrito (provincia_id, nombre) VALUES
(1, 'Lima'),
(1, 'Barranco'),
(1, 'La Molina'),
(1, 'Miraflores');

-- CENTRO DE RECICLAJE
INSERT INTO centro (usuario_id, nombre, direccion, distrito_id, tipo_id, telefono, estado) VALUES
(2, 'Centro Eco Lima', 'Av. Principal 123, La Molina', 3, 1, '987654322', 'activo');

-- REPRESENTANTE DEL CENTRO
INSERT INTO centro_representante (centro_id, ruc, razon_social, contacto_nombre, contacto_cargo, contacto_tel, contacto_email) VALUES
(1, '20123456789', 'Centro Ecológico Sostenible S.A.', 'María García López', 'Gerente', '987654322', 'contacto@centroeco.pe');

-- PRECIOS DE MATERIALES EN EL CENTRO (Solo materiales elegibles)
INSERT INTO centro_material_precio (centro_id, material_id, precio_kg, moneda) VALUES
(1, 1, 2.50, 'PEN'),
(1, 2, 2.30, 'PEN'),
(1, 3, 1.80, 'PEN'),
(1, 5, 0.50, 'PEN'),
(1, 7, 2.00, 'PEN'),
(1, 9, 1.50, 'PEN'),
(1, 16, 8.00, 'PEN'),
(1, 17, 3.50, 'PEN');


-- End file: scriptbd.sql


-- Begin file: sp_auth.sql



DROP PROCEDURE IF EXISTS sp_auth_usuario_obtener_por_email;
DELIMITER $$
CREATE PROCEDURE sp_auth_usuario_obtener_por_email(IN p_email VARCHAR(180))
BEGIN
  SELECT
    u.id, u.nombre, u.apellido_paterno, u.apellido_materno,
    u.email, u.telefono, u.fecha_nacimiento, u.avatar_key,
    u.estado, u.rol_id,
    r.clave AS rol_clave,
    ua.password_hash, ua.email_verificado, ua.email_verificado_en,
    ua.intentos_fallidos, ua.bloqueado_hasta
  FROM usuario u
  JOIN rol r ON r.id = u.rol_id
  LEFT JOIN usuario_auth ua ON ua.usuario_id = u.id
  WHERE u.email = p_email
  LIMIT 1;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS sp_auth_usuario_crear;
DELIMITER $$
CREATE PROCEDURE sp_auth_usuario_crear(
  IN p_nombre VARCHAR(120),
  IN p_apellido_paterno VARCHAR(120),
  IN p_apellido_materno VARCHAR(120),
  IN p_email VARCHAR(180),
  IN p_telefono VARCHAR(32),
  IN p_fecha_nacimiento DATE,
  IN p_avatar_key VARCHAR(600),
  IN p_password_hash VARCHAR(255),
  IN p_rol_clave VARCHAR(20)
)
BEGIN
  DECLARE v_rol_id TINYINT UNSIGNED;

  SELECT id INTO v_rol_id
    FROM rol
   WHERE clave = p_rol_clave
   LIMIT 1;

  IF v_rol_id IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Rol inválido';
  END IF;

  START TRANSACTION;

  INSERT INTO usuario
    (nombre, apellido_paterno, apellido_materno, email, telefono, fecha_nacimiento, avatar_key, estado, rol_id)
  VALUES
    (p_nombre, p_apellido_paterno, NULLIF(p_apellido_materno,''), p_email, p_telefono, p_fecha_nacimiento, p_avatar_key, 'activo', v_rol_id);

  INSERT INTO usuario_auth
    (usuario_id, password_hash, email_verificado, intentos_fallidos, bloqueado_hasta)
  VALUES
    (LAST_INSERT_ID(), p_password_hash, 0, 0, NULL);

  COMMIT;

  SELECT LAST_INSERT_ID() AS usuario_id;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS sp_auth_email_verificar;
DELIMITER $$
CREATE PROCEDURE sp_auth_email_verificar(IN p_usuario_id INT)
BEGIN
  UPDATE usuario_auth
     SET email_verificado = 1,
         email_verificado_en = NOW(),
         actualizado_en = NOW()
   WHERE usuario_id = p_usuario_id
   LIMIT 1;

  SELECT ROW_COUNT() AS affected;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS sp_auth_password_actualizar;
DELIMITER $$
CREATE PROCEDURE sp_auth_password_actualizar(
  IN p_usuario_id INT,
  IN p_password_hash VARCHAR(255)
)
BEGIN
  UPDATE usuario_auth
     SET password_hash = p_password_hash,
         actualizado_en = NOW()
   WHERE usuario_id = p_usuario_id
   LIMIT 1;

  SELECT ROW_COUNT() AS affected;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS sp_auth_intentos_reset;
DELIMITER $$
CREATE PROCEDURE sp_auth_intentos_reset(IN p_usuario_id INT)
BEGIN
  UPDATE usuario_auth
     SET intentos_fallidos = 0,
         bloqueado_hasta = NULL,
         actualizado_en = NOW()
   WHERE usuario_id = p_usuario_id
   LIMIT 1;

  SELECT ROW_COUNT() AS affected;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS sp_auth_intento_fallido;
DELIMITER $$
CREATE PROCEDURE sp_auth_intento_fallido(
  IN p_usuario_id INT,
  IN p_max_fails INT,
  IN p_lock_minutes INT
)
BEGIN
  UPDATE usuario_auth
     SET intentos_fallidos = LEAST(intentos_fallidos + 1, 255),
         bloqueado_hasta = CASE
           WHEN (intentos_fallidos + 1) >= p_max_fails
             THEN DATE_ADD(NOW(), INTERVAL p_lock_minutes MINUTE)
           ELSE bloqueado_hasta
         END,
         actualizado_en = NOW()
   WHERE usuario_id = p_usuario_id
   LIMIT 1;

  SELECT intentos_fallidos, bloqueado_hasta
    FROM usuario_auth
   WHERE usuario_id = p_usuario_id
   LIMIT 1;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS sp_auth_otp_upsert;
DELIMITER $$
CREATE PROCEDURE sp_auth_otp_upsert(
  IN p_usuario_id INT,
  IN p_tipo VARCHAR(30),
  IN p_codigo_hash CHAR(64),
  IN p_expira_en DATETIME
)
BEGIN
  INSERT INTO codigo_otp (usuario_id, tipo, codigo_hash, expira_en, usado, creado_en)
  VALUES (p_usuario_id, p_tipo, p_codigo_hash, p_expira_en, 0, NOW())
  ON DUPLICATE KEY UPDATE
    codigo_hash = VALUES(codigo_hash),
    expira_en   = VALUES(expira_en),
    usado       = 0,
    creado_en   = NOW();

  SELECT 1 AS ok;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS sp_auth_otp_usar_si_valido;
DELIMITER $$
CREATE PROCEDURE sp_auth_otp_usar_si_valido(
  IN p_usuario_id INT,
  IN p_tipo VARCHAR(30),
  IN p_codigo_hash CHAR(64)
)
BEGIN
  UPDATE codigo_otp
     SET usado = 1,
         usado_en = NOW()
   WHERE usuario_id = p_usuario_id
     AND tipo = p_tipo
     AND codigo_hash = p_codigo_hash
     AND usado = 0
     AND expira_en > NOW()
   LIMIT 1;

  SELECT ROW_COUNT() AS affected;
END$$
DELIMITER ;


-- End file: sp_auth.sql


-- Begin file: sp_ubigeo.sql



-- =========================
-- DEPARTAMENTO
-- =========================

DROP PROCEDURE IF EXISTS sp_ubigeo_departamento_list;
DELIMITER $$
CREATE PROCEDURE sp_ubigeo_departamento_list()
BEGIN
  SELECT id, nombre
    FROM departamento
   ORDER BY nombre;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS sp_ubigeo_departamento_get;
DELIMITER $$
CREATE PROCEDURE sp_ubigeo_departamento_get(IN p_id INT)
BEGIN
  SELECT id, nombre
    FROM departamento
   WHERE id = p_id
   LIMIT 1;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS sp_ubigeo_departamento_create;
DELIMITER $$
CREATE PROCEDURE sp_ubigeo_departamento_create(IN p_nombre VARCHAR(120))
BEGIN
  INSERT INTO departamento(nombre)
  VALUES (TRIM(p_nombre));

  SELECT LAST_INSERT_ID() AS id;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS sp_ubigeo_departamento_update;
DELIMITER $$
CREATE PROCEDURE sp_ubigeo_departamento_update(
  IN p_id INT,
  IN p_nombre VARCHAR(120)
)
BEGIN
  UPDATE departamento
     SET nombre = TRIM(p_nombre)
   WHERE id = p_id
   LIMIT 1;

  SELECT ROW_COUNT() AS affected;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS sp_ubigeo_departamento_delete;
DELIMITER $$
CREATE PROCEDURE sp_ubigeo_departamento_delete(IN p_id INT)
BEGIN
  -- Impedir borrar si tiene provincias
  IF EXISTS (SELECT 1 FROM provincia WHERE departamento_id = p_id LIMIT 1) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'No se puede eliminar: departamento tiene provincias';
  END IF;

  DELETE FROM departamento WHERE id = p_id LIMIT 1;
  SELECT ROW_COUNT() AS affected;
END$$
DELIMITER ;


-- =========================
-- PROVINCIA
-- =========================

DROP PROCEDURE IF EXISTS sp_ubigeo_provincia_list;
DELIMITER $$
CREATE PROCEDURE sp_ubigeo_provincia_list(IN p_departamento_id INT)
BEGIN
  SELECT id, departamento_id, nombre
    FROM provincia
   WHERE (p_departamento_id IS NULL OR departamento_id = p_departamento_id)
   ORDER BY nombre;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS sp_ubigeo_provincia_get;
DELIMITER $$
CREATE PROCEDURE sp_ubigeo_provincia_get(IN p_id INT)
BEGIN
  SELECT id, departamento_id, nombre
    FROM provincia
   WHERE id = p_id
   LIMIT 1;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS sp_ubigeo_provincia_create;
DELIMITER $$
CREATE PROCEDURE sp_ubigeo_provincia_create(
  IN p_departamento_id INT,
  IN p_nombre VARCHAR(120)
)
BEGIN
  INSERT INTO provincia(departamento_id, nombre)
  VALUES (p_departamento_id, TRIM(p_nombre));

  SELECT LAST_INSERT_ID() AS id;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS sp_ubigeo_provincia_update;
DELIMITER $$
CREATE PROCEDURE sp_ubigeo_provincia_update(
  IN p_id INT,
  IN p_departamento_id INT,
  IN p_nombre VARCHAR(120)
)
BEGIN
  UPDATE provincia
     SET departamento_id = p_departamento_id,
         nombre = TRIM(p_nombre)
   WHERE id = p_id
   LIMIT 1;

  SELECT ROW_COUNT() AS affected;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS sp_ubigeo_provincia_delete;
DELIMITER $$
CREATE PROCEDURE sp_ubigeo_provincia_delete(IN p_id INT)
BEGIN
  -- Impedir borrar si tiene distritos
  IF EXISTS (SELECT 1 FROM distrito WHERE provincia_id = p_id LIMIT 1) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'No se puede eliminar: provincia tiene distritos';
  END IF;

  DELETE FROM provincia WHERE id = p_id LIMIT 1;
  SELECT ROW_COUNT() AS affected;
END$$
DELIMITER ;


-- =========================
-- DISTRITO
-- =========================

DROP PROCEDURE IF EXISTS sp_ubigeo_distrito_list;
DELIMITER $$
CREATE PROCEDURE sp_ubigeo_distrito_list(IN p_provincia_id INT)
BEGIN
  SELECT id, provincia_id, nombre
    FROM distrito
   WHERE (p_provincia_id IS NULL OR provincia_id = p_provincia_id)
   ORDER BY nombre;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS sp_ubigeo_distrito_get;
DELIMITER $$
CREATE PROCEDURE sp_ubigeo_distrito_get(IN p_id INT)
BEGIN
  SELECT id, provincia_id, nombre
    FROM distrito
   WHERE id = p_id
   LIMIT 1;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS sp_ubigeo_distrito_create;
DELIMITER $$
CREATE PROCEDURE sp_ubigeo_distrito_create(
  IN p_provincia_id INT,
  IN p_nombre VARCHAR(120)
)
BEGIN
  INSERT INTO distrito(provincia_id, nombre)
  VALUES (p_provincia_id, TRIM(p_nombre));

  SELECT LAST_INSERT_ID() AS id;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS sp_ubigeo_distrito_update;
DELIMITER $$
CREATE PROCEDURE sp_ubigeo_distrito_update(
  IN p_id INT,
  IN p_provincia_id INT,
  IN p_nombre VARCHAR(120)
)
BEGIN
  UPDATE distrito
     SET provincia_id = p_provincia_id,
         nombre = TRIM(p_nombre)
   WHERE id = p_id
   LIMIT 1;

  SELECT ROW_COUNT() AS affected;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS sp_ubigeo_distrito_delete;
DELIMITER $$
CREATE PROCEDURE sp_ubigeo_distrito_delete(IN p_id INT)
BEGIN
  -- Impedir borrar si está usado por un centro
  IF EXISTS (SELECT 1 FROM centro WHERE distrito_id = p_id LIMIT 1) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'No se puede eliminar: distrito está usado por centros';
  END IF;

  DELETE FROM distrito WHERE id = p_id LIMIT 1;
  SELECT ROW_COUNT() AS affected;
END$$
DELIMITER ;


-- End file: sp_ubigeo.sql


-- Begin file: sp_materiales.sql

DELIMITER //

-- CATEGORÍA
DROP PROCEDURE IF EXISTS sp_admin_categoria_list;//
CREATE PROCEDURE sp_admin_categoria_list()
BEGIN
  SELECT id, nombre, icono, activo FROM material_categoria ORDER BY nombre;
END;//

DROP PROCEDURE IF EXISTS sp_admin_categoria_get;//
CREATE PROCEDURE sp_admin_categoria_get(IN p_id INT)
BEGIN
  SELECT id, nombre, icono, activo FROM material_categoria WHERE id = p_id LIMIT 1;
END;//

DROP PROCEDURE IF EXISTS sp_admin_categoria_create;//
CREATE PROCEDURE sp_admin_categoria_create(
  IN p_nombre VARCHAR(80), IN p_icono VARCHAR(600), IN p_activo TINYINT)
BEGIN
  INSERT INTO material_categoria (nombre, icono, activo) VALUES (p_nombre, p_icono, p_activo);
  SELECT LAST_INSERT_ID() AS id;
END;//

DROP PROCEDURE IF EXISTS sp_admin_categoria_update;//
CREATE PROCEDURE sp_admin_categoria_update(
  IN p_id INT, IN p_nombre VARCHAR(80), IN p_icono VARCHAR(600), IN p_activo TINYINT)
BEGIN
  UPDATE material_categoria SET nombre = p_nombre, icono = p_icono, activo = p_activo WHERE id = p_id;
  SELECT ROW_COUNT() AS affected;
END;//

DROP PROCEDURE IF EXISTS sp_admin_categoria_delete;//
CREATE PROCEDURE sp_admin_categoria_delete(IN p_id INT)
BEGIN
  DELETE FROM material_categoria WHERE id = p_id;
  SELECT ROW_COUNT() AS affected;
END;//

-- SUBCATEGORÍA
DROP PROCEDURE IF EXISTS sp_admin_subcategoria_list;//
CREATE PROCEDURE sp_admin_subcategoria_list(IN p_categoria_id INT)
BEGIN
  SELECT id, categoria_id, nombre, activo FROM material_subcategoria
    WHERE (p_categoria_id IS NULL OR categoria_id = p_categoria_id)
    ORDER BY nombre;
END;//

DROP PROCEDURE IF EXISTS sp_admin_subcategoria_get;//
CREATE PROCEDURE sp_admin_subcategoria_get(IN p_id INT)
BEGIN
  SELECT id, categoria_id, nombre, activo FROM material_subcategoria WHERE id = p_id LIMIT 1;
END;//

DROP PROCEDURE IF EXISTS sp_admin_subcategoria_create;//
CREATE PROCEDURE sp_admin_subcategoria_create(
  IN p_categoria_id INT, IN p_nombre VARCHAR(120), IN p_activo TINYINT)
BEGIN
  INSERT INTO material_subcategoria (categoria_id, nombre, activo) VALUES (p_categoria_id, p_nombre, p_activo);
  SELECT LAST_INSERT_ID() AS id;
END;//

DROP PROCEDURE IF EXISTS sp_admin_subcategoria_update;//
CREATE PROCEDURE sp_admin_subcategoria_update(
  IN p_id INT, IN p_categoria_id INT, IN p_nombre VARCHAR(120), IN p_activo TINYINT)
BEGIN
  UPDATE material_subcategoria SET categoria_id = p_categoria_id, nombre = p_nombre, activo = p_activo WHERE id = p_id;
  SELECT ROW_COUNT() AS affected;
END;//

DROP PROCEDURE IF EXISTS sp_admin_subcategoria_delete;//
CREATE PROCEDURE sp_admin_subcategoria_delete(IN p_id INT)
BEGIN
  DELETE FROM material_subcategoria WHERE id = p_id;
  SELECT ROW_COUNT() AS affected;
END;//

-- MATERIAL
DROP PROCEDURE IF EXISTS sp_admin_material_list;//
CREATE PROCEDURE sp_admin_material_list(
  IN p_subcategoria_id INT, IN p_activo TINYINT, IN p_elegible TINYINT, IN p_q VARCHAR(255))
BEGIN
  SELECT m.id,
         m.subcategoria_id,
         s.nombre AS subcategoria_nombre,
         s.categoria_id,
         c.nombre AS categoria_nombre,
         m.nombre,
         m.icono,
         m.elegible,
         m.activo
  FROM material m
  LEFT JOIN material_subcategoria s ON s.id = m.subcategoria_id
  LEFT JOIN material_categoria c ON c.id = s.categoria_id
  WHERE (p_subcategoria_id IS NULL OR m.subcategoria_id = p_subcategoria_id)
    AND (p_activo IS NULL OR m.activo = p_activo)
    AND (p_elegible IS NULL OR m.elegible = p_elegible)
    AND (
      p_q IS NULL OR p_q = ''
      OR (p_q REGEXP '^[0-9]+$' AND m.id = CAST(p_q AS UNSIGNED))
      OR m.nombre LIKE CONCAT('%', p_q, '%')
      OR s.nombre LIKE CONCAT('%', p_q, '%')
      OR c.nombre LIKE CONCAT('%', p_q, '%')
    )
  ORDER BY m.nombre;
END;//

DROP PROCEDURE IF EXISTS sp_admin_material_get;//
CREATE PROCEDURE sp_admin_material_get(IN p_id INT)
BEGIN
  SELECT m.id,
         m.subcategoria_id,
         s.nombre AS subcategoria_nombre,
         s.categoria_id,
         c.nombre AS categoria_nombre,
         m.nombre,
         m.icono,
         m.elegible,
         m.activo
  FROM material m
  LEFT JOIN material_subcategoria s ON s.id = m.subcategoria_id
  LEFT JOIN material_categoria c ON c.id = s.categoria_id
  WHERE m.id = p_id
  LIMIT 1;
END;//

DROP PROCEDURE IF EXISTS sp_admin_material_create;//
CREATE PROCEDURE sp_admin_material_create(
  IN p_subcategoria_id INT, IN p_nombre VARCHAR(120), IN p_icono VARCHAR(1000), IN p_elegible TINYINT, IN p_activo TINYINT)
BEGIN
  INSERT INTO material (subcategoria_id, nombre, icono, elegible, activo) VALUES (p_subcategoria_id, p_nombre, p_icono, p_elegible, p_activo);
  SELECT LAST_INSERT_ID() AS id;
END;//

DROP PROCEDURE IF EXISTS sp_admin_material_update;//
CREATE PROCEDURE sp_admin_material_update(
  IN p_id INT, IN p_subcategoria_id INT, IN p_nombre VARCHAR(120), IN p_icono VARCHAR(1000), IN p_elegible TINYINT, IN p_activo TINYINT)
BEGIN
  UPDATE material SET subcategoria_id = p_subcategoria_id, nombre = p_nombre, icono = p_icono, elegible = p_elegible, activo = p_activo WHERE id = p_id;
  SELECT ROW_COUNT() AS affected;
END;//

DROP PROCEDURE IF EXISTS sp_admin_material_delete;//
CREATE PROCEDURE sp_admin_material_delete(IN p_id INT)
BEGIN
  DELETE FROM material WHERE id = p_id;
  SELECT ROW_COUNT() AS affected;
END;//

-- MATERIAL INFO
DROP PROCEDURE IF EXISTS sp_admin_material_info_get;//
CREATE PROCEDURE sp_admin_material_info_get(IN p_material_id INT)
BEGIN
  SELECT material_id, descripcion, beneficios, proceso, ideas, contaminacion FROM material_info WHERE material_id = p_material_id LIMIT 1;
END;//

DROP PROCEDURE IF EXISTS sp_admin_material_info_upsert;//
CREATE PROCEDURE sp_admin_material_info_upsert(
  IN p_material_id INT, IN p_descripcion TEXT, IN p_beneficios TEXT, IN p_proceso TEXT, IN p_ideas TEXT, IN p_contaminacion TEXT)
BEGIN
  IF EXISTS (SELECT 1 FROM material_info WHERE material_id = p_material_id) THEN
    UPDATE material_info SET descripcion = p_descripcion, beneficios = p_beneficios, proceso = p_proceso, ideas = p_ideas, contaminacion = p_contaminacion WHERE material_id = p_material_id;
  ELSE
    INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion) VALUES (p_material_id, p_descripcion, p_beneficios, p_proceso, p_ideas, p_contaminacion);
  END IF;
END;//

DROP PROCEDURE IF EXISTS sp_admin_material_info_list;//
CREATE PROCEDURE sp_admin_material_info_list()
BEGIN
  SELECT mi.material_id,
         m.nombre AS material_nombre,
         m.icono AS material_icono,
         s.id AS subcategoria_id,
         s.nombre AS subcategoria_nombre,
         c.id AS categoria_id,
         c.nombre AS categoria_nombre,
         mi.descripcion,
         mi.beneficios,
         mi.proceso,
         mi.ideas,
         mi.contaminacion
  FROM material_info mi
  INNER JOIN material m ON m.id = mi.material_id
  LEFT JOIN material_subcategoria s ON s.id = m.subcategoria_id
  LEFT JOIN material_categoria c ON c.id = s.categoria_id
  ORDER BY m.nombre;
END;//

DROP PROCEDURE IF EXISTS sp_admin_material_info_delete;//
CREATE PROCEDURE sp_admin_material_info_delete(IN p_material_id INT)
BEGIN
  DELETE FROM material_info WHERE material_id = p_material_id;
  SELECT ROW_COUNT() AS affected;
END;//

DELIMITER ;


-- End file: sp_materiales.sql


-- Begin file: seed_material_info_by_name.sql

-- Seed material_info by matching material.nombre to avoid FK id mismatches


INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion)
SELECT m.id,
 'Botella PET transparente para bebidas. Fácil de compactar y reciclar.',
 'Reciclable en PET para fibra o envases',
 'Clasificar por color, limpiar y compactar antes de entrega',
 'Reutilizar como contenedores domésticos; donar a centros de acopio',
 'Baja contaminación si está vacía y enjuagada'
FROM material m
WHERE m.nombre = 'Botella PET transparente'
  AND NOT EXISTS (SELECT 1 FROM material_info mi WHERE mi.material_id = m.id);

INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion)
SELECT m.id,
 'Botella PET de color, similar a PET transparente pero con pigmentos.',
 'Reciclable aunque el color afecta algunas vías de reciclaje',
 'Separar por color cuando sea posible; limpiar y compactar',
 'Usos en manualidades o proyectos de arquitectura con botellas',
 'Pigmentos pueden limitar usos en reciclaje de alta calidad'
FROM material m
WHERE m.nombre = 'Botella PET de color'
  AND NOT EXISTS (SELECT 1 FROM material_info mi WHERE mi.material_id = m.id);

INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion)
SELECT m.id,
 'Bolsa HDPE (polietileno de alta densidad). Bolsas y film resistente.',
 'Alta tasa de reciclaje para productos plásticos y reciclados plásticos rígidos',
 'Limpiar de residuos y compactar en fardos',
 'Recolectar en puntos limpios para reciclaje industrial',
 'Si contiene residuos puede contaminar cargas'
FROM material m
WHERE m.nombre = 'Bolsa HDPE'
  AND NOT EXISTS (SELECT 1 FROM material_info mi WHERE mi.material_id = m.id);

INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion)
SELECT m.id,
 'Tubería PVC usada en construcción y saneamiento.',
 'Material recuperable para procesos específicos de reciclaje de PVC',
 'Separar de otros materiales, cortar en tramos y llevar a reciclador especializado',
 'Reusar en obras pequeñas o en jardinería para riego',
 'PVC con aditivos puede liberar contaminantes si se quema'
FROM material m
WHERE m.nombre = 'Tubería PVC' OR m.nombre = 'Tubería PVC'
  AND NOT EXISTS (SELECT 1 FROM material_info mi WHERE mi.material_id = m.id);

INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion)
SELECT m.id,
 'Botella de vidrio clara. Envases de beverages y frascos.',
 'Reciclable indefinidamente en nuevas botellas o vidrio triturado',
 'Separar por color cuando tienda lo pida; retirar tapas metálicas',
 'Reutilizar frascos como envases o decoración',
 'Vidrio roto puede causar riesgos físicos pero no contamina químicamente'
FROM material m
WHERE m.nombre = 'Botella clara' OR m.nombre = 'Botella de vidrio clara'
  AND NOT EXISTS (SELECT 1 FROM material_info mi WHERE mi.material_id = m.id);

INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion)
SELECT m.id,
 'Frasco transparente de vidrio (uso doméstico y farmacéutico).',
 'Mismo tratamiento que botellas de vidrio; alto valor en reciclaje',
 'Lavar y clasificar por color; separar tapas',
 'Reutilizar como contenedor para alimentos secos',
 'Vidrio contaminado con residuos químicos requiere manejo especial'
FROM material m
WHERE m.nombre = 'Frasco transparente'
  AND NOT EXISTS (SELECT 1 FROM material_info mi WHERE mi.material_id = m.id);

INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion)
SELECT m.id,
 'Botella verde de vidrio.',
 'Reciclable en corridas de vidrio verde; buen valor para recicladores',
 'Separar por color y limpiar',
 'Reutilizar en huertos o manualidades',
 'Vidrio sucio contamina cargas de reciclaje'
FROM material m
WHERE m.nombre = 'Botella verde'
  AND NOT EXISTS (SELECT 1 FROM material_info mi WHERE mi.material_id = m.id);

INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion)
SELECT m.id,
 'Periódico impreso. Papel con tintas y anuncios.',
 'Reciclable para pasta de papel y cartón',
 'Quitar partes no papel (plásticos, metal); compactar',
 'Usar como compostador o material de embalaje',
 'Papel muy sucio reduce calidad de reciclaje'
FROM material m
WHERE m.nombre = 'Periódico'
  AND NOT EXISTS (SELECT 1 FROM material_info mi WHERE mi.material_id = m.id);

INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion)
SELECT m.id,
 'Cartón corrugado. Cajas y embalajes.',
 'Alta reutilización y reciclaje; se convierte en nuevo cartón',
 'Desarmar cajas, quitar cintas y compactar',
 'Reusar cajas para mudanzas o almacenamiento',
 'Humedad y aceites degradan la fibra'
FROM material m
WHERE m.nombre = 'Cartón de caja' OR m.nombre = 'Cartón corrugado'
  AND NOT EXISTS (SELECT 1 FROM material_info mi WHERE mi.material_id = m.id);

INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion)
SELECT m.id,
 'Papel de oficina blanco. Hojas y folletos.',
 'Reciclable en papel de oficina y cartón',
 'Separar de papel contaminado; empaquetar limpio',
 'Reutilizar para notas internas o donaciones',
 'Papel con soportes plásticos/metal contamina'
FROM material m
WHERE m.nombre = 'Papel de oficina' OR m.nombre = 'Papel blanco'
  AND NOT EXISTS (SELECT 1 FROM material_info mi WHERE mi.material_id = m.id);

INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion)
SELECT m.id,
 'Lata de aluminio. Envase de bebidas y alimentos.',
 'Altamente reciclable y de alto valor económico',
 'Aplastar y separar de otros metales; llevar a centro de reciclaje',
 'Reutilizar para manualidades o pequeños recipientes',
 'Restos de alimentos pueden contaminar si no se limpian'
FROM material m
WHERE m.nombre = 'Lata de aluminio'
  AND NOT EXISTS (SELECT 1 FROM material_info mi WHERE mi.material_id = m.id);

INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion)
SELECT m.id,
 'Papel aluminio. Láminas y envolturas.',
 'Reciclable si está limpio y separado de plásticos',
 'Limpiar restos y compactar en bola para facilitar reciclaje',
 'Reutilizar para cocinar o manualidades',
 'Restos de comida contaminan el flujo de reciclaje'
FROM material m
WHERE m.nombre = 'Papel aluminio'
  AND NOT EXISTS (SELECT 1 FROM material_info mi WHERE mi.material_id = m.id);

INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion)
SELECT m.id,
 'Tubo de acero. Material estructural y de instalaciones.',
 'Acero 100% reciclable con amplio mercado',
 'Separar de otros metales y recubrimientos; entregar a chatarrería',
 'Reusar en estructuras o mobiliario',
 'Recubrimientos pueden requerir tratamiento previo'
FROM material m
WHERE m.nombre = 'Tubo de acero' OR m.nombre = 'Tubo de acero'
  AND NOT EXISTS (SELECT 1 FROM material_info mi WHERE mi.material_id = m.id);

INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion)
SELECT m.id,
 'Cable de cobre. Conductores eléctricos con alto valor.',
 'Cobre tiene alto precio y valor de recuperación',
 'Retirar aislamiento cuando sea posible; entregar a chatarrería',
 'Reutilizar como conductor o vender a reciclador',
 'Aislamientos plásticos deben eliminarse para evitar contaminación'
FROM material m
WHERE m.nombre = 'Cable de cobre'
  AND NOT EXISTS (SELECT 1 FROM material_info mi WHERE mi.material_id = m.id);

INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion)
SELECT m.id,
 'Gasas quirúrgicas contaminadas. Residuos biomédicos peligrosos.',
 'NO ACEPTAR para acopio; requieren gestión como residuo sanitario',
 'Manipular con EPP; disposición por gestor autorizado',
 'No reutilizar; enviar a tratamiento especializado (incineración o autoclave)',
 'Alta contaminación biológica, riesgo para salud'
FROM material m
WHERE m.nombre = 'Gasas quirúrgicas contaminadas'
  AND NOT EXISTS (SELECT 1 FROM material_info mi WHERE mi.material_id = m.id);

INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion)
SELECT m.id,
 'Agujas y jeringas. Residuos punzocortantes y biológicos.',
 'NO ACEPTAR en acopios; manejar como residuo peligroso',
 'Utilizar contenedores puncture-proof y gestores autorizados',
 'No manipular; transporte y disposición por empresa autorizada',
 'Riesgo de infección y contaminación biológica'
FROM material m
WHERE m.nombre = 'Agujas y jeringas'
  AND NOT EXISTS (SELECT 1 FROM material_info mi WHERE mi.material_id = m.id);

INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion)
SELECT m.id,
 'Sangre y fluidos corporales. Residuos clínicos peligrosos.',
 'NO ACEPTAR; gestionar como residuo hospitalario',
 'Recolección por sistema sanitario; tratamiento especializado',
 'N/A',
 'Alto riesgo biológico que requiere contención y tratamiento'
FROM material m
WHERE m.nombre = 'Sangre y fluidos corporales'
  AND NOT EXISTS (SELECT 1 FROM material_info mi WHERE mi.material_id = m.id);

INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion)
SELECT m.id,
 'Ácido sulfúrico. Producto químico corrosivo y peligroso.',
 'NO ACEPTAR en acopios; gestiona por gestor de residuos químicos',
 'Almacenamiento en recipientes adecuados; transportar por empresa autorizada',
 'N/A',
 'Alta contaminación química y riesgo de corrosión'
FROM material m
WHERE m.nombre = 'Ácido sulfúrico' OR m.nombre = 'Ácido sulfúrico'
  AND NOT EXISTS (SELECT 1 FROM material_info mi WHERE mi.material_id = m.id);

INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion)
SELECT m.id,
 'Pesticidas. Productos fitosanitarios tóxicos.',
 'NO ACEPTAR; tratamiento por gestor de residuos peligrosos',
 'No verter; devolver a puntos de recogida especializados',
 'N/A',
 'Contaminación química significativa del suelo y agua'
FROM material m
WHERE m.nombre = 'Pesticidas'
  AND NOT EXISTS (SELECT 1 FROM material_info mi WHERE mi.material_id = m.id);

-- End of seed by name


-- End file: seed_material_info_by_name.sql


-- Begin file: seed_material_info.sql

-- Seed data for material_info


INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion) VALUES
(1, 'Botella PET transparente para bebidas. Fácil de compactar y reciclar.', 'Reciclable en PET para fibra o envases', 'Clasificar por color, limpiar y compactar antes de entrega', 'Reutilizar como contenedores domésticos; donar a centros de acopio', 'Baja contaminación si está vacía y enjuagada'),
(2, 'Botella PET de color, similar a PET transparente pero con pigmentos.', 'Reciclable aunque el color afecta algunas vías de reciclaje', 'Separar por color cuando sea posible; limpiar y compactar', 'Usos en manualidades o proyectos de arquitectura con botellas', 'Pigmentos pueden limitar usos en reciclaje de alta calidad'),
(3, 'Bolsa HDPE (polietileno de alta densidad). Bolsas y film resistente.', 'Alta tasa de reciclaje para productos plásticos y reciclados plásticos rígidos', 'Limpiar de residuos y compactar en fardos', 'Recolectar en puntos limpios para reciclaje industrial', 'Si contiene residuos puede contaminar cargas'),
(4, 'Tubería PVC usada en construcción y saneamiento.', 'Material recuperable para procesos específicos de reciclaje de PVC', 'Separar de otros materiales, cortar en tramos y llevar a reciclador especializado', 'Reusar en obras pequeñas o en jardinería para riego', 'PVC con aditivos puede liberar contaminantes si se quema'),
(5, 'Botella de vidrio clara. Envases de bebidas y frascos.', 'Reciclable indefinidamente en nuevas botellas o vidrio triturado', 'Separar por color cuando tienda lo pida; retirar tapas metálicas', 'Reutilizar frascos como envases o decoración', 'Vidrio roto puede causar riesgos físicos pero no contamina químicamente'),
(6, 'Frasco transparente de vidrio (uso doméstico y farmacéutico).', 'Mismo tratamiento que botellas de vidrio; alto valor en reciclaje', 'Lavar y clasificar por color; separar tapas', 'Reutilizar como contenedor para alimentos secos', 'Vidrio contaminado con residuos químicos requiere manejo especial'),
(7, 'Botella verde de vidrio.', 'Reciclable en corridas de vidrio verde; buen valor para recicladores', 'Separar por color y limpiar', 'Reutilizar en huertos o manualidades', 'Vidrio sucio contamina cargas de reciclaje'),
(8, 'Botella marrón de vidrio.', 'Reciclable, común en envases de cerveza', 'Separar por color y enjuagar', 'Reutilizar o donar a centros de acopio', 'Riesgo físico si está roto'),
(9, 'Periódico impreso. Papel con tintas y anuncios.', 'Reciclable para pasta de papel y cartón', 'Quitar partes no papel (plásticos, metal); compactar', 'Usar como compostador o material de embalaje', 'Papel muy sucio reduce calidad de reciclaje'),
(10, 'Cartón corrugado. Cajas y embalajes.', 'Alta reutilización y reciclaje; se convierte en nuevo cartón', 'Desarmar cajas, quitar cintas y compactar', 'Reusar cajas para mudanzas o almacenamiento', 'Humedad y aceites degradan la fibra'),
(11, 'Papel de oficina blanco. Hojas y folletos.', 'Reciclable en papel de oficina y cartón', 'Separar de papel contaminado; empaquetar limpio', 'Reutilizar para notas internas o donaciones', 'Papel con soportes plásticos/metal contamina'),
(12, 'Lata de aluminio. Envase de bebidas y alimentos.', 'Altamente reciclable y de alto valor económico', 'Aplastar y separar de otros metales; llevar a centro de reciclaje', 'Reutilizar para manualidades o pequeños recipientes', 'Restos de alimentos pueden contaminar si no se limpian'),
(13, 'Papel aluminio. Láminas y envolturas.', 'Reciclable si está limpio y separado de plásticos', 'Limpiar restos y compactar en bola para facilitar reciclaje', 'Reutilizar para cocinar o manualidades', 'Restos de comida contaminan el flujo de reciclaje'),
(14, 'Tubo de acero. Material estructural y de instalaciones.', 'Acero 100% reciclable con amplio mercado', 'Separar de otros metales y recubrimientos; entregar a chatarrería', 'Reusar en estructuras o mobiliario', 'Recubrimientos pueden requerir tratamiento previo'),
(15, 'Cable de cobre. Conductores eléctricos con alto valor.', 'Cobre tiene alto precio y valor de recuperación', 'Retirar aislamiento cuando sea posible; entregar a chatarrería', 'Reutilizar como conductor o vender a reciclador', 'Aislamientos plásticos deben eliminarse para evitar contaminación'),
(16, 'Gasas quirúrgicas contaminadas. Residuos biomédicos peligrosos.', 'NO ACEPTAR para acopio; requieren gestión como residuo sanitario', 'Manipular con EPP; disposición por gestor autorizado', 'No reutilizar; enviar a tratamiento especializado (incineración o autoclave)', 'Alta contaminación biológica, riesgo para salud'),
(17, 'Agujas y jeringas. Residuos punzocortantes y biológicos.', 'NO ACEPTAR en acopios; manejar como residuo peligroso', 'Utilizar contenedores puncture-proof y gestores autorizados', 'No manipular; transporte y disposición por empresa autorizada', 'Riesgo de infección y contaminación biológica'),
(18, 'Sangre y fluidos corporales. Residuos clínicos peligrosos.', 'NO ACEPTAR; gestionar como residuo hospitalario', 'Recolección por sistema sanitario; tratamiento especializado', 'N/A', 'Alto riesgo biológico que requiere contención y tratamiento'),
(19, 'Ácido sulfúrico. Producto químico corrosivo y peligroso.', 'NO ACEPTAR en acopios; gestiona por gestor de residuos químicos', 'Almacenamiento en recipientes adecuados; transportar por empresa autorizada', 'N/A', 'Alta contaminación química y riesgo de corrosión'),
(20, 'Pesticidas. Productos fitosanitarios tóxicos.', 'NO ACEPTAR; tratamiento por gestor de residuos peligrosos', 'No verter; devolver a puntos de recogida especializados', 'N/A', 'Contaminación química significativa del suelo y agua');

-- Fin seed material_info


-- End file: seed_material_info.sql

