# run_all_sql.ps1
# Concatenate SQL files in order into combined.sql and optionally execute it
# Usage: .\run_all_sql.ps1 -DbUser root -DbName manosverdes -Run
param(
  [string]$DbUser = "root",
  [string]$DbHost = "localhost",
  [string]$DbName = "manosverdes",
  [switch]$Run,
  [switch]$Force
)

$files = @(
  "script.sql",
  "scriptbd.sql",
  "sp_auth.sql",
  "sp_ubigeo.sql",
  "sp_materiales.sql",
  "seed_material_info_by_name.sql",
  "seed_material_info.sql"
)

$root = Split-Path -Path $MyInvocation.MyCommand.Definition -Parent
$combined = Join-Path $root "combined.sql"

Write-Host "Generating $combined from files:" -ForegroundColor Cyan
$files | ForEach-Object { Write-Host " - $_" }

if (Test-Path $combined -and -not $Force) {
  $ans = Read-Host "File combined.sql already exists. Overwrite? (y/N)"
  if ($ans -notin @('y','Y')) { Write-Host 'Aborting.'; exit 0 }
}

# Header: ensure a single DB create + use
$header = @(
  "DROP DATABASE IF EXISTS $DbName;",
  "CREATE DATABASE $DbName CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;",
  "USE $DbName;",
  "\n-- Combined generated by run_all_sql.ps1\n"
)

Set-Content -Path $combined -Value ($header -join "`n") -Encoding UTF8

foreach ($f in $files) {
  $path = Join-Path $root $f
  if (-not (Test-Path $path)) { Write-Warning "Skipping missing file: $f"; continue }
  Write-Host "Appending $f..."
  $lines = Get-Content $path -Raw -Encoding UTF8 -ErrorAction Stop

  # Remove duplicated DB creation / USE lines from source files
  $lines = $lines -replace "(?im)^\s*DROP\s+DATABASE\s+IF\s+EXISTS.*$", ""
  $lines = $lines -replace "(?im)^\s*CREATE\s+DATABASE.*$", ""
  $lines = $lines -replace "(?im)^\s*USE\s+manosverdes;?", ""

  # Append marker and content
  Add-Content -Path $combined -Value "`n-- Begin file: $f`n" -Encoding UTF8
  Add-Content -Path $combined -Value $lines -Encoding UTF8
  Add-Content -Path $combined -Value "`n-- End file: $f`n" -Encoding UTF8
}

Write-Host "Combined SQL written to: $combined" -ForegroundColor Green

if ($Run) {
  # prompt for password securely
  $pwd = Read-Host -Prompt "MySQL password for user $DbUser" -AsSecureString
  $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($pwd)
  $plain = [Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)

  Write-Host "Executing combined.sql against $DbHost/$DbName as $DbUser..." -ForegroundColor Cyan
  $cmd = "mysql.exe -h $DbHost -u $DbUser -p$plain $DbName < `"$combined`""
  Write-Host "Running: $cmd"
  iex $cmd
  $LASTEXIT = $LASTEXITCODE
  if ($LASTEXIT -eq 0) { Write-Host 'Execution completed successfully.' -ForegroundColor Green } else { Write-Error "mysql returned exit code $LASTEXIT" }
}
else {
  Write-Host "Run with -Run to execute the generated combined.sql against your database." -ForegroundColor Yellow
}
