-- Seed data for material_info
USE manosverdes;

INSERT INTO material_info (material_id, descripcion, beneficios, proceso, ideas, contaminacion) VALUES
(1, 'Botella PET transparente para bebidas. Fácil de compactar y reciclar.', 'Reciclable en PET para fibra o envases', 'Clasificar por color, limpiar y compactar antes de entrega', 'Reutilizar como contenedores domésticos; donar a centros de acopio', 'Baja contaminación si está vacía y enjuagada'),
(2, 'Botella PET de color, similar a PET transparente pero con pigmentos.', 'Reciclable aunque el color afecta algunas vías de reciclaje', 'Separar por color cuando sea posible; limpiar y compactar', 'Usos en manualidades o proyectos de arquitectura con botellas', 'Pigmentos pueden limitar usos en reciclaje de alta calidad'),
(3, 'Bolsa HDPE (polietileno de alta densidad). Bolsas y film resistente.', 'Alta tasa de reciclaje para productos plásticos y reciclados plásticos rígidos', 'Limpiar de residuos y compactar en fardos', 'Recolectar en puntos limpios para reciclaje industrial', 'Si contiene residuos puede contaminar cargas'),
(4, 'Tubería PVC usada en construcción y saneamiento.', 'Material recuperable para procesos específicos de reciclaje de PVC', 'Separar de otros materiales, cortar en tramos y llevar a reciclador especializado', 'Reusar en obras pequeñas o en jardinería para riego', 'PVC con aditivos puede liberar contaminantes si se quema'),
(5, 'Botella de vidrio clara. Envases de bebidas y frascos.', 'Reciclable indefinidamente en nuevas botellas o vidrio triturado', 'Separar por color cuando tienda lo pida; retirar tapas metálicas', 'Reutilizar frascos como envases o decoración', 'Vidrio roto puede causar riesgos físicos pero no contamina químicamente'),
(6, 'Frasco transparente de vidrio (uso doméstico y farmacéutico).', 'Mismo tratamiento que botellas de vidrio; alto valor en reciclaje', 'Lavar y clasificar por color; separar tapas', 'Reutilizar como contenedor para alimentos secos', 'Vidrio contaminado con residuos químicos requiere manejo especial'),
(7, 'Botella verde de vidrio.', 'Reciclable en corridas de vidrio verde; buen valor para recicladores', 'Separar por color y limpiar', 'Reutilizar en huertos o manualidades', 'Vidrio sucio contamina cargas de reciclaje'),
(8, 'Botella marrón de vidrio.', 'Reciclable, común en envases de cerveza', 'Separar por color y enjuagar', 'Reutilizar o donar a centros de acopio', 'Riesgo físico si está roto'),
(9, 'Periódico impreso. Papel con tintas y anuncios.', 'Reciclable para pasta de papel y cartón', 'Quitar partes no papel (plásticos, metal); compactar', 'Usar como compostador o material de embalaje', 'Papel muy sucio reduce calidad de reciclaje'),
(10, 'Cartón corrugado. Cajas y embalajes.', 'Alta reutilización y reciclaje; se convierte en nuevo cartón', 'Desarmar cajas, quitar cintas y compactar', 'Reusar cajas para mudanzas o almacenamiento', 'Humedad y aceites degradan la fibra'),
(11, 'Papel de oficina blanco. Hojas y folletos.', 'Reciclable en papel de oficina y cartón', 'Separar de papel contaminado; empaquetar limpio', 'Reutilizar para notas internas o donaciones', 'Papel con soportes plásticos/metal contamina'),
(12, 'Lata de aluminio. Envase de bebidas y alimentos.', 'Altamente reciclable y de alto valor económico', 'Aplastar y separar de otros metales; llevar a centro de reciclaje', 'Reutilizar para manualidades o pequeños recipientes', 'Restos de alimentos pueden contaminar si no se limpian'),
(13, 'Papel aluminio. Láminas y envolturas.', 'Reciclable si está limpio y separado de plásticos', 'Limpiar restos y compactar en bola para facilitar reciclaje', 'Reutilizar para cocinar o manualidades', 'Restos de comida contaminan el flujo de reciclaje'),
(14, 'Tubo de acero. Material estructural y de instalaciones.', 'Acero 100% reciclable con amplio mercado', 'Separar de otros metales y recubrimientos; entregar a chatarrería', 'Reusar en estructuras o mobiliario', 'Recubrimientos pueden requerir tratamiento previo'),
(15, 'Cable de cobre. Conductores eléctricos con alto valor.', 'Cobre tiene alto precio y valor de recuperación', 'Retirar aislamiento cuando sea posible; entregar a chatarrería', 'Reutilizar como conductor o vender a reciclador', 'Aislamientos plásticos deben eliminarse para evitar contaminación'),
(16, 'Gasas quirúrgicas contaminadas. Residuos biomédicos peligrosos.', 'NO ACEPTAR para acopio; requieren gestión como residuo sanitario', 'Manipular con EPP; disposición por gestor autorizado', 'No reutilizar; enviar a tratamiento especializado (incineración o autoclave)', 'Alta contaminación biológica, riesgo para salud'),
(17, 'Agujas y jeringas. Residuos punzocortantes y biológicos.', 'NO ACEPTAR en acopios; manejar como residuo peligroso', 'Utilizar contenedores puncture-proof y gestores autorizados', 'No manipular; transporte y disposición por empresa autorizada', 'Riesgo de infección y contaminación biológica'),
(18, 'Sangre y fluidos corporales. Residuos clínicos peligrosos.', 'NO ACEPTAR; gestionar como residuo hospitalario', 'Recolección por sistema sanitario; tratamiento especializado', 'N/A', 'Alto riesgo biológico que requiere contención y tratamiento'),
(19, 'Ácido sulfúrico. Producto químico corrosivo y peligroso.', 'NO ACEPTAR en acopios; gestiona por gestor de residuos químicos', 'Almacenamiento en recipientes adecuados; transportar por empresa autorizada', 'N/A', 'Alta contaminación química y riesgo de corrosión'),
(20, 'Pesticidas. Productos fitosanitarios tóxicos.', 'NO ACEPTAR; tratamiento por gestor de residuos peligrosos', 'No verter; devolver a puntos de recogida especializados', 'N/A', 'Contaminación química significativa del suelo y agua');

-- Fin seed material_info
